apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-container
          image: AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/nodejs-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
