apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-container
        image: <YOUR_ECR_IMAGE_URI>:latest  # 🛠️ Replace via GitHub Actions or ArgoCD
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
