############################################
# Namespace Configuration for Node.js App
############################################
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
############################################
# Deployment for Node.js App from AWS ECR
############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/nodejs-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
      imagePullSecrets:
        - name: ecr-secret
---
############################################
# Service to Expose Node.js App
############################################
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo-app
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
############################################
# Optional Ingress (if needed)
############################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: demo-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 80
