spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/your-org/your-repo.git
    path: path/to/your/k8s/manifests
    targetRevision: HEAD
